// generated by Fast Light User Interface Designer (fluid) version 2.0100

#ifndef eiconsconf_h
#define eiconsconf_h
#include <fltk/Window.h>
extern fltk::Window* iconsConfWindow;
#include <fltk/Button.h>
#include <fltk/TabGroup.h>
#include <fltk/Group.h>
extern fltk::Button* colorButton;
extern fltk::Button* colorButton1;
#include <fltk/ValueSlider.h>
extern fltk::ValueSlider* maxWidthSlider;
extern fltk::ValueSlider* fontsizeSlider;
extern fltk::ValueSlider* gridspaceSlider;
#include <fltk/CheckButton.h>
extern fltk::CheckButton* autoArrButton;
extern fltk::CheckButton* engageButton;
extern fltk::CheckButton* bg_color_check;
void changeBoxColor(fltk::Button *box);
#endif
