#!/bin/sh

dump_config() {
	cat > $1 <<EOF
#
# Do not edit this file. Edit configure.in and m4/*.m4 files
# and run './autogen.sh' again.
#
EOF
	# a cool trict from autojam
	autoconf --trace=AC_SUBST \
  	| sed -e 's/configure.in:[0-9]*:AC_SUBST:\([^:]*\).*/\1 ?= "@\1@" ;/g' \
	| sed -e '/ac_*/d' -e '/ECHO_*/d' \
	| sort -u \
  	>> $1

	echo 'INSTALL_DIR ?= "@INSTALL_DIR@" ;' >> $1
}

if aclocal -I m4 && autoheader && autoconf; then
	#dump_config "Jamconfig.in"
	rm -f "config.h.in~"

	echo ""
	echo "Now run ./configure [OPTIONS]"
	echo "or './configure --help' to see them"
else
	echo ""
	echo "We failed :(. There should be some output, right ?"
	exit 1
fi
