#!/bin/sh

if aclocal -I m4 && autoheader && autoconf; then
	conffile="Jamconfig.in"

	echo "#" > $conffile
	echo "# Do not edit this file. Edit configure.in and *.m4 files" >> $conffile 
	echo "# and run './prepare'" >> $conffile
	echo "#" >> $conffile
	echo "" >> $conffile

	# a cool trict from autojam
	autoconf --trace=AC_SUBST \
  	| sed -e 's/configure.in:[0-9]*:AC_SUBST:\([^:]*\).*/\1 ?= "@\1@" ;/g' \
	| sed -e '/ac_*/d' -e '/ECHO_*/d' \
	| sort -u \
  	>> $conffile

	echo 'INSTALL_DIR ?= "@INSTALL_DIR@" ;' >> $conffile

	# a junk from autoheader
	rm -f "edeconf.h.in~"

	echo ""
	echo "Now run ./configure [OPTIONS]"
	echo "or './configure --help' to see them"
else
	echo ""
	echo "We failed :(. There should be some output, right ?"
	exit 1
fi
