// generated by Extended Fast Light User Interface Designer (eFluid) version 2.0003

#ifndef _ABOUTDIALOG_H_
#define _ABOUTDIALOG_H_

/*#include <efltk/Fl.h>
#include <efltk/Fl_Locale.h>
#include <efltk/Fl_Window.h>
#include <efltk/Fl_Box.h>
#include <efltk/Fl_Button.h>
#include <efltk/Fl_Divider.h>*/
#include <fltk/Fl.h>
//#include <fltk/Locale.h>
#include <fltk/Window.h>
#include <fltk/Box.h>
#include <fltk/Button.h>
#include <fltk/Divider.h>


void AboutDialog(fltk::Widget*, void*);

#endif
