// generated by Fast Light User Interface Designer (fluid) version 2.0100

#ifndef ecolorconf_h
#define ecolorconf_h
#include <fltk/Window.h>
extern fltk::Window* windowColorSettings;
#include <fltk/TabGroup.h>
#include <fltk/Group.h>
#include <fltk/Button.h>
extern void ChangeBoxColor(fltk::Button*, void*);
extern fltk::Button* colorBox;
extern fltk::Button* labelColorBox;
extern fltk::Button* selectionColorBox;
extern fltk::Button* selectionTextColorBox;
extern fltk::Button* highlightColorBox;
extern fltk::Button* highlightLabelColorBox;
extern fltk::Button* textColorBox;
extern fltk::Button* backgroundBox;
extern fltk::Button* textBackgroundBox;
extern fltk::Button* tooltipBox;
extern fltk::Button* tooltipTextColorButton;
#include <fltk/CheckButton.h>
extern fltk::CheckButton* tooltipsEnableEffects;
extern fltk::CheckButton* tooltipsEnable;
#include <fltk/Choice.h>
extern fltk::Choice* tooltipsEffectType;
#include <fltk/Item.h>
#include <fltk/ValueInput.h>
extern fltk::ValueInput* tooltipsDelay;
extern fltk::Button* setLabelFont;
extern fltk::Button* setTextFont;
#include <fltk/InvisibleBox.h>
extern fltk::InvisibleBox* labelFontInput;
extern fltk::InvisibleBox* textFontInput;
extern fltk::CheckButton* menusEnableEffects;
extern fltk::CheckButton* menusEnableSubwindowEffects;
extern fltk::Choice* menusEffectType;
extern fltk::ValueInput* menusSpeed;
extern fltk::ValueInput* menusDelay;
extern fltk::CheckButton* mdiAnimation;
extern fltk::CheckButton* mdiOpaqueAnimation;
extern fltk::CheckButton* imagesStateEffect;
extern fltk::CheckButton* allApplyRadioButton;
#include <fltk/InputBrowser.h>
extern fltk::InputBrowser* schemeListBox;
void ChangeBoxColor(fltk::Button *box, void *);
#endif
