#!/usr/bin/env perl
# A tool to generate some html-ized documentation
# based on capone source... see it as doxygen for capone.

sub write_prolog {
	print <<EOL
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>$_[0]</title>
<style type="text/css">
body {
   margin: 0;
   padding: 0;
   text-align: center;
}

.content {
   margin: 0 auto;
   padding: 10px 0 0 0;
   width: 83%;
   text-align: left;
}

h5.function {
   margin: 5px 0 5px 0;
   padding: 0;

   color: #527bbd;
   font-weight: bold;
   font-size: 120%;
}

h5.example {
   margin: 0;
   padding-bottom: 0.3em;
}

pre {
   margin: 0;
   padding: 0.6em 0.2em 0.2em 0.2em;
   color: black;
   background: #f4f4f4;
   border: 1px solid silver;
}

.footer {
   padding: 20px 0 10px 0;
   text-align: center;
   font-size: 80%;
}
</style>
</head>
<body>
<div class="content">
EOL
}

sub write_epilog {
	print <<EOL
</div> <!-- content -->
<div class="footer">generated with capone-doc</div>
</body>
</html>
EOL
}

sub main {
	if(@ARGV eq 0) {
		print "Usage: capone-doc [FILE] [TITLE]\n";
		print "Generate html-ized documentation by extracting documentation\n";
		print "specific tags on the specific manner from capone source file\n";
		return;
	}

	$in_block = 0;
	$filename = $ARGV[0];

	if($ARGV[1] eq "") {
		$title = $filename . " documentation";
	} else {
		$title = $ARGV[1];
	}

	open(INFILE, $filename) or die "Can't open $filename: $!";

	&write_prolog($title);

	while(<INFILE>) {
		# find markers
		if(/^;;=/) {
			if($in_block eq 0) {
				print "<div class=\"segment\">\n";
				$in_block = 1;
			} else {
				print "</div> <!-- segment -->\n";
				print "<br />\n";
				$in_block = 0;
			}

			# strip them
			s/;;=(.*)$//;
		}

		if($in_block eq 1) {
			# strip comments
			s/;;\s*\n$/<br \/>\n/;
			s/;;//;

			# \code and \endcode
			s/\\code/ <h5 class="example">Example:<\/h5>\n<pre>/;
			s/\\endcode/ <\/pre>/;

			# \func
			s/\\func (.*)/ <h5 class="function">$1<\/h5>/;

			# \param
			s/\\param (.*)/ <b>parameter:<\/b> $1<br \/>/;

			# \return
			s/\\return (.*)/ <b>returns:<\/b> $1<br \/>/;

			# \syntax
			s/\\syntax (.*)/ <b>syntax:<\/b> <i>$1<\/i><br \/>/;

			# \br
			s/\\br/<br \/>/g;

			# \center
			s/\\center (.*)$/<center>$1<\/center>/;

			# grok everything out
			print $_;
		}
	}

	&write_epilog;
}

&main;
