// generated by Fast Light User Interface Designer (fluid) version 2.0100

#include "edeskconf.h"
/*
 * $Id$
 *
 * Desktop icons manager
 * Part of Equinox Desktop Environment (EDE).
 * Copyright (c) 2000-2006 EDE Authors.
 *
 * This program is licenced under terms of the
 * GNU General Public Licence version 2 or newer.
 * See COPYING for details.
 */
//#include <efltk/Fl.h>
//#include <efltk/fl_ask.h>
//#include <efltk/Fl_Color_Chooser.h>
//#include <efltk/Fl_Config.h>
//#include <efltk/Fl_Image.h>
//#include <efltk/Fl_File_Dialog.h>
#include "eiconman.h"

fltk::Window *bg_prop_window=(fltk::Window *)0;

fltk::InvisibleBox *mini_image_box=(fltk::InvisibleBox *)0;

fltk::LightButton *color_button=(fltk::LightButton *)0;

fltk::CheckButton *use_button=(fltk::CheckButton *)0;

fltk::Group *bg_image_group=(fltk::Group *)0;

fltk::Input *image_input=(fltk::Input *)0;

static fltk::Button *browse_button=(fltk::Button *)0;

fltk::ValueSlider *opacity_slider=(fltk::ValueSlider *)0;

fltk::Choice *mode_choice=(fltk::Choice *)0;

static void cb_Cancel(fltk::Button*, void*) {
  bg_prop_window->do_callback();
}

void make_desktop_properties() {
  fltk::Window* w;
   {fltk::Window* o = bg_prop_window = new fltk::Window(560, 270, "Background settings");
    w = o;
    o->callback((fltk::Callback*)bg_prop_cb);
    ((fltk::Window*)(o))->hotspot(o);
    o->begin();
     {fltk::Group* o = new fltk::Group(10, 20, 265, 209, "Background");
      o->box(fltk::BORDER_FRAME);
      o->color((fltk::Color)0xe6e7e600);
      o->textcolor((fltk::Color)0xaaadaa00);
      o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
      o->begin();
       {fltk::InvisibleBox* o = new fltk::InvisibleBox(1, 1, 263, 207);
        o->box(fltk::BORDER_FRAME);
        o->color((fltk::Color)0xe6e7e600);
        o->textcolor((fltk::Color)0xdcdedc00);
      }
       {fltk::Group* o = new fltk::Group(35, 16, 230, 159);
        o->begin();
         {fltk::InvisibleBox* o = new fltk::InvisibleBox(65, 129, 60, 7);
          o->box(fltk::BORDER_BOX);
        }
         {fltk::InvisibleBox* o = new fltk::InvisibleBox(5, 0, 180, 131);
          o->box(fltk::THIN_UP_BOX);
        }
         {fltk::InvisibleBox* o = new fltk::InvisibleBox(47, 134, 94, 12);
          o->box(fltk::THIN_UP_BOX);
        }
         {fltk::InvisibleBox* o = new fltk::InvisibleBox(159, 121, 15, 6);
          o->box(fltk::THIN_UP_BOX);
        }
         {fltk::InvisibleBox* o = new fltk::InvisibleBox(152, 121, 2, 5);
          o->set_vertical();
          o->box(fltk::FLAT_BOX);
          o->color((fltk::Color)2);
        }
         {fltk::InvisibleBox* o = new fltk::InvisibleBox(15, 9, 160, 110);
          o->box(fltk::THIN_DOWN_BOX);
        }
         {fltk::InvisibleBox* o = mini_image_box = new fltk::InvisibleBox(16, 10, 158, 108);
          o->box(fltk::FLAT_BOX);
          o->buttonbox(fltk::FLAT_BOX);
          o->color((fltk::Color)32);
          o->highlight_color((fltk::Color)32);
          o->align(fltk::ALIGN_CENTER);
        }
        o->end();
      }
       {fltk::LightButton* o = color_button = new fltk::LightButton(169, 175, 85, 25, "C&olor...");
        o->type(0);
        o->box(fltk::THIN_UP_BOX);
        o->set_flag(fltk::VALUE);
        o->callback((fltk::Callback*)bg_image_color);
      }
      o->end();
    }
     {fltk::CheckButton* o = use_button = new fltk::CheckButton(285, 20, 265, 20, "Use wallpaper");
      o->set_flag(fltk::VALUE);
      o->callback((fltk::Callback*)bg_image_use);
    }
    new fltk::Divider("label");
     {fltk::Group* o = bg_image_group = new fltk::Group(285, 50, 265, 175);
      o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
      o->begin();
       {fltk::Input* o = image_input = new fltk::Input(20, 15, 240, 23, "Image:");
        o->callback((fltk::Callback*)bg_image_input);
        o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
        o->when(fltk::WHEN_ENTER_KEY);
      }
       {fltk::Button* o = browse_button = new fltk::Button(180, 48, 80, 23, "&Browse...");
        o->callback((fltk::Callback*)bg_image_browse);
      }
       {fltk::ValueSlider* o = opacity_slider = new fltk::ValueSlider(65, 83, 195, 18, "Opacity:");
        o->maximum(255);
        o->step(1.01);
        o->slider_size(10);
        o->callback((fltk::Callback*)bg_image_opacity);
        o->align(fltk::ALIGN_LEFT);
        o->when(fltk::WHEN_RELEASE);
        o->step(1);
      }
       {fltk::Choice* o = mode_choice = new fltk::Choice(65, 112, 195, 23, "Mode:");
        o->callback((fltk::Callback*)bg_image_mode);
        o->begin();
         {fltk::Item* o = new fltk::Item("Center");
          o->user_data((void*)(0));
        }
         {fltk::Item* o = new fltk::Item("Stretch");
          o->user_data((void*)(1));
        }
         {fltk::Item* o = new fltk::Item("Stretch (aspect)");
          o->user_data((void*)(2));
        }
         {fltk::Item* o = new fltk::Item("Tiled");
          o->deactivate();
        }
        o->end();
      }
      o->end();
    }
    new fltk::Divider("label");
     {fltk::Button* o = new fltk::Button(290, 240, 80, 25, "&OK");
      o->callback((fltk::Callback*)bg_ok);
    }
     {fltk::Button* o = new fltk::Button(380, 240, 80, 25, "&Apply");
      o->callback((fltk::Callback*)bg_apply);
    }
     {fltk::Button* o = new fltk::Button(470, 240, 80, 25, "&Cancel");
      o->callback((fltk::Callback*)cb_Cancel);
    }
    o->end();
    o->resizable(o);
  }
}
