// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef propdialog_h
#define propdialog_h
#include <fltk/Window.h>
extern fltk::Window* i_propertieswindow;
#include <fltk/TabGroup.h>
#include <fltk/Group.h>
extern fltk::Group* i_icontab;
#include <fltk/InvisibleBox.h>
extern fltk::InvisibleBox* pr_icon;
extern fltk::InvisibleBox* pr_name;
extern fltk::InvisibleBox* pr_size;
extern fltk::InvisibleBox* pr_exec;
extern fltk::Group* i_settingstab;
#include <fltk/Output.h>
extern fltk::Output* i_link;
#include <fltk/Input.h>
extern fltk::Input* i_name;
extern fltk::Input* i_location;
#include <fltk/Button.h>
extern fltk::Input* i_filename;
void property_dialog(fltk::Widget *, Icon *icon, bool show_settings);
#endif
