
CPPFILES = about_dialog.cpp Config.cpp Icon.cpp MimeType.cpp process.cpp pty.cpp Run.cpp Util.cpp
TARGET   =

include ../makeinclude

all: about_dialog.o Config.o Icon.o MimeType.o process.o pty.o Run.o Util.o

install:

uninstall:

clean:
	$(RM) *.o

