// generated by Fast Light User Interface Designer (fluid) version 2.0100

#ifndef ekeyconf_h
#define ekeyconf_h
#include "Shortcut_Button.h"
#include <fltk/Window.h>
extern fltk::Window* iconsConfWindow;
#include <fltk/Button.h>
#include <fltk/TabGroup.h>
#include <fltk/Group.h>
#include <fltk/InvisibleBox.h>
extern Shortcut_Button* shortcut;
#include <fltk/InputBrowser.h>
extern fltk::InputBrowser* action;
extern fltk::Window* newShortcutWindow;
#include <fltk/Input.h>
extern fltk::Input* shortcutName;
extern fltk::Input* shortcutCommand;
#endif
